Create Software-engineer-union.md
The-Brains/Ideas pull request #11
Opened 2017-10-08 20:05 UTC by Wonay

2017-10-09 20:28 UTC, jacklehamster requested changes

2017-10-09 20:28 UTC, jacklehamster commented on Business/Software-engineer-union.md
> +* Make sure that all software engineers get free 100% helath insurrance, vision covers
health

2017-10-10 00:30 UTC, Wonay commented on Business/Software-engineer-union.md
> +* Make sure that all software engineers get free 100% helath insurrance, vision covers
done

2017-10-10 06:50 UTC, jacklehamster approved these changes

2017-10-10 19:22 UTC, merged